version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Node.js runtime..."

  pre_build:
    commands:
      - echo "Welcome to my CICD pipeline"
  build:
    commands:
      # Running the node.js app| install dependencies, etc.
      - echo "Building Project..!!!!"
      - echo "Build started on `date`"
      - npm ci
      - npm install pm2 --save-dev
      - npm run start

      # Building Docker image
      - echo "Building Docker image"
      - docker build -t nodejs-repo .  
      
      # Logging in to Amazon ECR
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 678270849957.dkr.ecr.us-east-1.amazonaws.com
  
  post_build:
    commands:
      # Pushing Docker image to ECR
      - echo "Pushing Docker image to ECR!!!!!!"
      - docker tag nodejs-repo:latest 678270849957.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo:latest     
      - docker push 678270849957.dkr.ecr.us-east-1.amazonaws.com/nodejs-repo:latest
      - echo "Build completed on `date`" 

artifacts:
  files:
    - '**/*'

  cache:
    paths:
      - '/root/.npm/**/*'